import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navigation from './components/navigation/navigation.component';
import { UserProvider } from './context/user.context';

const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'CodePuzzle Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <Navigation/>
          <main className='lg:ml-[150px] lg:mr-[150px] mx-auto pb-[20px] lg:mt-[100px] mt-[360px]'>
          {children}
          </main>
        </UserProvider>
      </body>
    </html>
  )
}
